language: php

php:
  - 5.6
  - 7

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
 - phpunit --verbose --debug --coverage-clover=coverage.clover

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
